package com.example.mobilecwk_02

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "meal")
data class meal(
    @PrimaryKey val id: Int,
    val Meal: String,
    val DrinkAlternate: String?,
    val Category: String,
    val Area: String,
    val Instructions: String?,
    val MealThumb: String?,
    val Tags: String,
    val Youtube: String,
    val Ingredient1: String?,
    val Ingredient2: String?,
    val Ingredient3: String?,
    val Ingredient4: String?,
    val Ingredient5: String?,
    val Ingredient6: String?,
    val Ingredient7: String?,
    val Ingredient8: String?,
    val Ingredient9: String?,
    val Ingredient10: String?,
    val Ingredient11: String?,
    val Ingredient12: String?,
    val Ingredient13: String?,
    val Ingredient14: String?,
    val Ingredient15: String?,
    val Ingredient16: String?,
    val Ingredient17: String?,
    val Ingredient18: String?,
    val Ingredient19: String?,
    val Ingredient20: String?,
    val Measure1: String?,
    val Measure2: String?,
    val Measure3: String?,
    val Measure4: String?,
    val Measure5: String?,
    val Measure6: String?,
    val Measure7: String?,
    val Measure8: String?,
    val Measure9: String?,
    val Measure10: String?,
    val Measure11: String?,
    val Measure12: String?,
    val Measure13: String?,
    val Measure14: String?,
    val Measure15: String?,
    val Measure16: String?,
    val Measure17: String?,
    val Measure18: String?,
    val Measure19: String?,
    val Measure20: String?,
    val Measure21: String?,
    val Source: String?,
    val ImageSource: String?,
    val CreativeCommonsConfirmed: String?,
    val dateModified: String?,
    val Thumbnail: String?,
)
